general:
   verboseout: True
   includetext: True # switch to determine whether text fields are included in model
   presaved: False # switch to determine whether to train model or load saved model
   savemodel: False # switch to determine whether to save model
   picklemodel: True # switch for code to allow pickling of Keras model
   save_model_plot: False
   tensorboard_callback: False
   hctextmax: 7000
   maxwords: 6000
   textmax: 50
   pickled_data_file: '20142018_0930.pkl'
   pickled_dataframe: '2014_2019_df_cleaned_remove_bad_values_may16_2020.pkl'
   route_direction_file: 'routedirection.csv'
   modifier: 'may16_2020'
   targetthresh: 6.0 # use as boundary between delay and no delay
   targetcontinuous: False # switch to determine whether target is continuous
   emptythresh: 6000
   zero_weight: 1.0 # class_weight = {0 : zero_weight, 1: one_weight}
   one_weight: 45.878 # default one_weight
   one_weight_offset: 0 # additional offset to one_weight
   patience_threshold: 15
   start_year: 2014 # date of start of refactored dataset
   start_month: 1
   start_day: 1
   end_year: 2019 # date of end of refactored dataset
   end_month: 12
   end_day: 31
test_parms:
   testproportion: 0.2 # proportion of data reserved for test set
   trainproportion: 0.8 # proportion of non-test data dedicated to training (vs. validation)
   current_experiment: 5
   repeatable_run: False # switch to control whether runs are repeated identically
   get_test_train_acc: True # switch to control whether block to get test and train accuracy is after training
hyperparameters:
   learning_rate: 0.001
   dropout_rate: 0.0003 #0.003
   l2_lambda: 0.0003 #7.5
   loss_func: "binary_crossentropy"
   output_activation: "hard_sigmoid" # set to "linear" if target is continuous
   batch_size: 1000
   epochs: 50